### ISSUE TITLE
Practica 9 - Diagrama de secuencia

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-hjfs#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 9 Diagrama de Secuencia (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-hjfs/files/10191657/Practica.9.Diagrama.de.Secuencia.Federico.Victoriano.Sierra.pdf)

**Comment by SANDRAVELASCO** [comment]
[Práctica 9 Diagrama de Secuencia (Sandra Gabriela Velasco Guzmán).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-hjfs/files/10191683/Practica.9.Diagrama.de.Secuencia.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 9 Diagrama de Secuencia (José Antonio Blbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-hjfs/files/10191690/Practica.9.Diagrama.de.Secuencia.Jose.Antonio.Blbuena.Cruz.pdf)

**Comment by Heidi-19** [comment]
[Práctica 9 Diagrama de Secuencia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-hjfs/files/10191748/Practica.9.Diagrama.de.Secuencia.pdf)

**Comment by Valentiin01** [comment]
Calificación 50

**Comment by josealfredo79** [comment]
Falta el objetivo de la practica

**Comment by josealfredo79** [comment]
Calificacion 48
